apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webservice
  name: webservice-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
      - image: 1471238641122.dkr.ecr.eu-central-1.amazonaws.com/webservice:latest
        name: webservice-container
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: 200Mi
          requests:
            cpu: "100m"
            memory: 100Mi
